//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adfc.Msbuild {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adfc.Msbuild.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;type&quot;: &quot;object&quot;,
        ///    &quot;properties&quot;: { 
        ///        &quot;$schema&quot;: {
        ///            &quot;type&quot;: &quot;string&quot;
        ///        }
        ///    },
        ///    &quot;patternProperties&quot;: {
        ///        &quot;^[a-zA-Z]&quot;: {
        ///            &quot;type&quot;: &quot;array&quot;,
        ///            &quot;items&quot;: {
        ///                &quot;type&quot;: &quot;object&quot;,
        ///                &quot;properties&quot;: {
        ///                    &quot;name&quot;: {
        ///                        &quot;type&quot;: &quot;string&quot;,
        ///                        &quot;pattern&quot;: &quot;(^\\$\\.[a-zA-z][a-zA-Z0-9]*(\\.[a-zA-z][a-zA-z0-9]*)*)&quot;
        ///                    },
        ///                    &quot;value&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Microsoft_DataFactory_Config {
            get {
                return ResourceManager.GetString("Microsoft_DataFactory_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: &quot;http://datafactories.schema.management.azure.com/schemas/2015-09-01/Microsoft.DataFactory.LinkedService.json&quot;,
        ///    &quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema#&quot;,
        ///    &quot;title&quot;: &quot;Microsoft.Azure.Management.DataFactories.Models.LinkedService&quot;,
        ///    &quot;description&quot;: &quot;The data factory linkedService.&quot;,
        ///    &quot;type&quot;: &quot;object&quot;,
        ///    &quot;required&quot;: [
        ///        &quot;name&quot;,
        ///        &quot;properties&quot;
        ///    ],
        ///    &quot;properties&quot;: {
        ///        &quot;name&quot;: {
        ///            &quot;description&quot;: &quot;Data factory linkedService name.&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Microsoft_DataFactory_LinkedService {
            get {
                return ResourceManager.GetString("Microsoft_DataFactory_LinkedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: &quot;http://datafactories.schema.management.azure.com/schemas/2015-09-01/Microsoft.DataFactory.Pipeline.json&quot;,
        ///    &quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema#&quot;,
        ///    &quot;title&quot;: &quot;Microsoft.Azure.Management.DataFactories.Models.Pipeline&quot;,
        ///    &quot;description&quot;: &quot;A pipeline defines activities.&quot;,
        ///    &quot;type&quot;: &quot;object&quot;,
        ///    &quot;required&quot;: [
        ///        &quot;name&quot;,
        ///        &quot;properties&quot;
        ///    ],
        ///    &quot;properties&quot;: {
        ///        &quot;name&quot;: {
        ///            &quot;description&quot;: &quot;Name of the pipeline.&quot;,
        ///            &quot;type&quot;: &quot;s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Microsoft_DataFactory_Pipeline {
            get {
                return ResourceManager.GetString("Microsoft_DataFactory_Pipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: &quot;http://datafactories.schema.management.azure.com/schemas/2015-09-01/Microsoft.DataFactory.Table.json&quot;,
        ///    &quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema#&quot;,
        ///    &quot;title&quot;: &quot;Microsoft.Azure.Management.DataFactories.Models.Table&quot;,
        ///    &quot;description&quot;: &quot;A table defines the schema of the data as well as its storage.&quot;,
        ///    &quot;type&quot;: &quot;object&quot;,
        ///    &quot;required&quot;: [
        ///        &quot;name&quot;,
        ///        &quot;properties&quot;
        ///    ],
        ///    &quot;properties&quot;: {
        ///        &quot;name&quot;: {
        ///            &quot;description&quot;: &quot;Name of the table.&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Microsoft_DataFactory_Table {
            get {
                return ResourceManager.GetString("Microsoft_DataFactory_Table", resourceCulture);
            }
        }
    }
}
